// Generated by tools/generate-addon-script-names.php from Mojang's bedrock-samples script metadata 1.26.50.4. Do not edit.
// Every name @minecraft/common exports in the game, so any pack's imports link. The hand-written module
// re-exports this file and its own implementations take precedence; the stubs below throw only when used.

const unavailable = (name) => class{ constructor(){ throw new ReferenceError(`${name} is not available on this server`); } };
const error = (name) => { const E = class extends Error{ constructor(message){ super(message); this.name = name; } }; Object.defineProperty(E, "name", { value: name }); return E; };

export const ArgumentOutOfBoundsError = error("ArgumentOutOfBoundsError");
export const ContainerSizeOutOfBoundsError = error("ContainerSizeOutOfBoundsError");
export const EngineError = error("EngineError");
export const InvalidArgumentError = error("InvalidArgumentError");
export const PropertyOutOfBoundsError = error("PropertyOutOfBoundsError");
export const RuntimeConditionError = error("RuntimeConditionError");
export const UnsupportedFunctionalityError = error("UnsupportedFunctionalityError");
export const InvalidArgumentErrorType = Object.freeze({ Duplicate: "Duplicate", Empty: "Empty", Unknown: "Unknown", Unspecified: "Unspecified", InvalidType: "InvalidType", UnsupportedValue: "UnsupportedValue" });
