// Generated by tools/generate-addon-script-names.php from Mojang's bedrock-samples script metadata 1.26.50.4. Do not edit.
// Every name @minecraft/diagnostics exports in the game, so any pack's imports link. The hand-written module
// re-exports this file and its own implementations take precedence; the stubs below throw only when used.

const unavailable = (name) => class{ constructor(){ throw new ReferenceError(`${name} is not available on this server`); } };
const error = (name) => { const E = class extends Error{ constructor(message){ super(message); this.name = name; } }; Object.defineProperty(E, "name", { value: name }); return E; };

export const SentryAlreadyInitializedError = error("SentryAlreadyInitializedError");
export const SentryUninitializedError = error("SentryUninitializedError");
export const Sentry = unavailable("Sentry");
export const SentryEventLevel = Object.freeze({ debug: "debug", error: "error", fatal: "fatal", info: "info", warning: "warning" });
export const sentry = undefined;
