<?php

/*
 *
 *  ____            _        _   __  __ _                  __  __ ____
 * |  _ \ ___   ___| | _____| |_|  \/  (_)_ __   ___      |  \/  |  _ \
 * | |_) / _ \ / __| |/ / _ \ __| |\/| | | '_ \ / _ \_____| |\/| | |_) |
 * |  __/ (_) | (__|   <  __/ |_| |  | | | | | |  __/_____| |  | |  __/
 * |_|   \___/ \___|_|\_\___|\__|_|  |_|_|_| |_|\___|     |_|  |_|_|
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author PocketMine Team
 * @link http://www.pocketmine.net/
 *
 *
 */

declare(strict_types=1);

/**
 * Generates resources/addon_scripts/<module>-names.mjs: every class, enum, constant, error, function and object the
 * game's @minecraft script modules export, as the union over all 1.x, 2.x and beta versions in Mojang's
 * bedrock-samples metadata (https://github.com/Mojang/bedrock-samples, the metadata/ folder). An add-on script
 * that imports a name its module does not export fails to load entirely, so the hand-written modules re-export
 * these; their own implementations take precedence, and the generated stubs throw only when used.
 *
 * Usage: php tools/generate-addon-script-names.php <path to bedrock-samples/metadata>
 */

namespace pocketmine\tools\generate_addon_script_names;

use function array_keys;
use function basename;
use function count;
use function dirname;
use function file_get_contents;
use function file_put_contents;
use function fwrite;
use function glob;
use function implode;
use function is_array;
use function is_dir;
use function is_file;
use function json_decode;
use function json_encode;
use function ksort;
use function preg_match;
use function preg_replace;
use function preg_split;
use function sort;
use function sprintf;
use function ucfirst;
use const JSON_UNESCAPED_SLASHES;
use const JSON_UNESCAPED_UNICODE;
use const PHP_EOL;
use const STDERR;

/** Our module file => metadata file prefixes (the -bindings files hold the definitions). */
const MODULES = [
	"server" => ["server-bindings"],
	"server-ui" => ["server-ui-bindings", "server-ui"],
	"common" => ["common"],
	"server-admin" => ["server-admin"],
	"server-net" => ["server-net"],
	"server-gametest" => ["server-gametest"],
	"debug-utilities" => ["debug-utilities"],
	"diagnostics" => ["diagnostics"],
	"server-graphics" => ["server-graphics"],
];

function js(mixed $value) : string{
	return (string) json_encode($value, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
}

function ident(string $name) : bool{
	return preg_match('/^[A-Za-z_$][\w$]*$/', $name) === 1;
}

if(count($argv) !== 2 || !is_dir($argv[1] . "/script_modules")){
	fwrite(STDERR, "Usage: php " . basename(__FILE__) . " <path to bedrock-samples/metadata>" . PHP_EOL);
	exit(1);
}
$meta = $argv[1];
$version = "";
if(is_file(dirname($meta) . "/version.json")){
	$versions = json_decode((string) file_get_contents(dirname($meta) . "/version.json"), true);
	$version = is_array($versions) ? (string) ($versions["latest"]["version"] ?? "") : "";
}
$out = dirname(__DIR__) . "/resources/addon_scripts";

foreach(MODULES as $target => $prefixes){
	$classes = $enums = $constants = $errors = $functions = $objects = [];
	$files = [];
	foreach($prefixes as $prefix){
		$files = [...$files, ...(glob("$meta/script_modules/@minecraft/{$prefix}_*.json") ?: [])];
	}
	sort($files);
	foreach($files as $file){
		$d = json_decode((string) file_get_contents($file), true);
		if(!is_array($d)){
			continue;
		}
		foreach($d["classes"] ?? [] as $c){
			$classes[$c["name"]] = true;
		}
		foreach($d["enums"] ?? [] as $e){
			foreach($e["constants"] ?? [] as $c){
				$enums[$e["name"]][$c["name"]] ??= $c["value"] ?? $c["name"];
			}
			$enums[$e["name"]] ??= [];
		}
		foreach($d["constants"] ?? [] as $c){
			if(isset($c["value"])){
				$constants[$c["name"]] ??= $c["value"];
			}
		}
		foreach($d["errors"] ?? [] as $e){
			$errors[$e["name"]] = true;
		}
		foreach($d["functions"] ?? [] as $f){
			$functions[$f["name"]] = true;
		}
		foreach($d["objects"] ?? [] as $o){
			$objects[$o["name"]] = true;
		}
	}
	if($classes === [] && $enums === [] && $errors === [] && $functions === []){
		continue;
	}
	ksort($classes);
	ksort($enums);
	ksort($constants);
	ksort($errors);
	ksort($functions);
	ksort($objects);

	$lines = [
		"// Generated by tools/generate-addon-script-names.php from Mojang's bedrock-samples script metadata" . ($version !== "" ? " $version" : "") . ". Do not edit.",
		"// Every name @minecraft/$target exports in the game, so any pack's imports link. The hand-written module",
		"// re-exports this file and its own implementations take precedence; the stubs below throw only when used.",
		"",
		'const unavailable = (name) => class{ constructor(){ throw new ReferenceError(`${name} is not available on this server`); } };',
		'const error = (name) => { const E = class extends Error{ constructor(message){ super(message); this.name = name; } }; Object.defineProperty(E, "name", { value: name }); return E; };',
		"",
	];
	foreach(array_keys($errors) as $name){
		if(ident($name)){
			$lines[] = "export const $name = error(" . js($name) . ");";
		}
	}
	foreach(array_keys($classes) as $name){
		if(ident($name) && !isset($errors[$name])){
			$lines[] = "export const $name = unavailable(" . js($name) . ");";
		}
	}
	foreach($enums as $name => $values){
		if(ident($name)){
			$members = [];
			foreach($values as $key => $value){
				$members[] = (ident((string) $key) ? $key : js((string) $key)) . ": " . js($value);
			}
			$lines[] = "export const $name = Object.freeze({ " . implode(", ", $members) . " });";
		}
	}
	foreach($constants as $name => $value){
		if(ident($name) && !isset($enums[$name])){
			$lines[] = "export const $name = " . js($value) . ";";
		}
	}
	foreach(array_keys($functions) as $name){
		if(ident($name)){
			$lines[] = "export function $name(){ throw new ReferenceError(" . js("$name is not available on this server") . "); }";
		}
	}
	foreach(array_keys($objects) as $name){
		if(ident($name) && !isset($constants[$name])){
			$lines[] = "export const $name = undefined;";
		}
	}
	file_put_contents("$out/$target-names.mjs", implode("\n", $lines) . "\n");
	echo sprintf("%s: %d classes, %d enums, %d errors from %d files", $target, count($classes), count($enums), count($errors), count($files)) . PHP_EOL;
}

/** vanilla_data_type in the metadata => the @minecraft/vanilla-data export */
const VANILLA_DATA = [
	"biome" => "MinecraftBiomeTypes",
	"block" => "MinecraftBlockTypes",
	"cameraPresets" => "MinecraftCameraPresetsTypes",
	"cooldownCategory" => "MinecraftCooldownCategoryTypes",
	"dimension" => "MinecraftDimensionTypes",
	"effect" => "MinecraftEffectTypes",
	"enchantment" => "MinecraftEnchantmentTypes",
	"entity" => "MinecraftEntityTypes",
	"feature" => "MinecraftFeatureTypes",
	"item" => "MinecraftItemTypes",
	"potionEffect" => "MinecraftPotionEffectTypes",
	"potionDelivery" => "MinecraftPotionDeliveryTypes",
];

/** "minecraft:music_disc_13" => "MusicDisc13", as @minecraft/vanilla-data names its members */
function pascal(string $id) : string{
	$name = preg_replace('/^[a-z0-9_]+:/', '', $id) ?? $id;
	$out = "";
	foreach(preg_split('/[^A-Za-z0-9]+/', $name) ?: [] as $part){
		$out .= ucfirst($part);
	}
	return $out;
}

$lines = [
	"// Generated by tools/generate-addon-script-names.php from Mojang's bedrock-samples vanilla data" . ($version !== "" ? " $version" : "") . ". Do not edit.",
	"// The identifiers @minecraft/vanilla-data exports, member for member.",
	"",
];
$count = 0;
foreach(glob("$meta/vanilladata_modules/*.json") ?: [] as $file){
	$d = json_decode((string) file_get_contents($file), true);
	$export = is_array($d) ? (VANILLA_DATA[$d["vanilla_data_type"] ?? ""] ?? null) : null;
	if($export === null){
		continue;
	}
	$members = [];
	foreach($d["data_items"] ?? [] as $item){
		$id = (string) ($item["name"] ?? "");
		$key = pascal($id);
		if($key !== "" && ident($key)){
			$members[$key] = $id;
		}
	}
	ksort($members);
	$body = [];
	foreach($members as $key => $id){
		$body[] = "$key: " . js($id);
	}
	$lines[] = "export const $export = Object.freeze({ " . implode(", ", $body) . " });";
	$count += count($members);
}
file_put_contents("$out/vanilla-data-names.mjs", implode("\n", $lines) . "\n");
echo "vanilla-data: $count identifiers" . PHP_EOL;
